### ISSUE TITLE
fails on my pictures

### ISSUE THREAD

**Issue by dicarne** [DavidBuchanan314/ambiguous-png-packer#8]
```
$ python pack.py 1.png 2.png out.png
Traceback (most recent call last):
  File "pack.py", line 186, in <module>
    main(*sys.argv[1:4])
  File "pack.py", line 120, in main
    b += acomp
TypeError: can't concat bool to bytes
```
The example runs fine on windows, but it fails to run with other pictures. Are there any special requirements for pictures?

**Comment by dicarne** [comment]
before error, the "False" return from here
![image](https://user-images.githubusercontent.com/10357789/147246694-83993c88-84db-4618-9cdf-39d7d70a8bd6.png)

**Comment by DavidBuchanan314** [comment]
See #5

**Comment by mnixry** [comment]
Change the `False` to `b""` works for me, but it may cause corrupt image sometime
